### ISSUE TITLE
Märk puudu

### ISSUE THREAD

**Issue by ooker** [saaremaavald/saarlus#2]
Aino Kallas, siin failis
https://github.com/saaremaavald/saarlus/blob/master/content/_lood/aino-kallas.md peaks olema mingi kirjavahemärk originaaltekstis.

*Sellegi kohta oldi ühel arvamisel, et nägusamat ja kokkusobivamat paari võis vaevalt laternaga otsida \[**SIIN**\] poiss pikk ja uhke, uljas rühilt, peas juba mehe meel ja soontes tuld; tüdruk veetlev, nagu armastusele loodud.*

**Comment by meritkarise** [comment]
KOOLON. M
